Add shopping cart model
RomanSoproniuk/online-book-store pull request #12
Opened 2024-03-19 19:12 UTC by RomanSoproniuk

2024-03-19 19:54 UTC, okuzan requested changes
remove redundancy in subpackages, dto/categorydto to dto/category etc

2024-03-19 19:54 UTC, okuzan commented on src/main/java/book/store/onlinebookstore/mapper/ShoppingCartMapper.java
> +
```suggestion
    @Mapping(target = "usersId", source = "user", qualifiedByName = "getUserId")
    ShoppingCartResponseDto toDto(ShoppingCart cart);
```

2024-03-19 19:54 UTC, okuzan commented on src/main/java/book/store/onlinebookstore/model/CartItem.java
> +@SQLDelete(sql = "UPDATE cart_items SET is_deleted = true WHERE id=?")
```suggestion
@SQLDelete(sql = "UPDATE cart_items SET is_deleted = TRUE WHERE id = ?")
```

2024-03-19 19:54 UTC, okuzan commented on src/main/java/book/store/onlinebookstore/model/ShoppingCart.java
> +@SQLDelete(sql = "UPDATE shopping_carts SET is_deleted = true WHERE id=?")
```suggestion
@SQLDelete(sql = "UPDATE shopping_carts SET is_deleted = TRUE WHERE id = ?")
```

2024-03-19 19:54 UTC, okuzan commented on src/main/java/book/store/onlinebookstore/repository/shoppingcart/ShoppingCartRepository.java
> +
```suggestion
```

2024-03-19 19:54 UTC, okuzan commented on src/main/resources/db/changelog/db.changelog-master.yaml
> +      file: db/changelog/changes/012-create-cart-items-table.yaml
```suggestion
      file: db/changelog/changes/012-create-cart-items-table.yaml

```

2024-03-19 19:54 UTC, okuzan commented on src/main/java/book/store/onlinebookstore/service/CartItemService.java
> +
```suggestion
```

2024-03-20 11:07 UTC, kozhukhovsky approved these changes

2024-03-20 11:08 UTC, merged