Add order api
RomanSoproniuk/online-book-store pull request #13
Opened 2024-03-20 16:20 UTC by RomanSoproniuk

2024-03-20 18:57 UTC, olekskov requested changes

2024-03-20 18:57 UTC, olekskov commented on src/main/java/book/store/onlinebookstore/service/impl/OrderServiceImpl.java
> +        orderItemRepository.saveAll(orderItems);
cannot see where cart is cl;eared after order is formed

2024-03-20 18:57 UTC, olekskov commented on src/main/java/book/store/onlinebookstore/service/impl/OrderItemServiceImpl.java
> +    }
These methods are called from API available to any user.
If I call them with random Id I have a lot of chances to see what someone else is buying.
Need to implement logic that user can see only own orders and items by id

2024-03-21 10:53 UTC, kozhukhovsky approved these changes

2024-03-21 12:50 UTC, merged