Add shopping cart test
RomanSoproniuk/online-book-store pull request #16
Opened 2024-03-29 20:07 UTC by RomanSoproniuk

![controller](https://github.com/RomanSoproniuk/online-book-store/assets/151533079/5cf59470-da7b-440e-a355-2492acbb0e2e)
![repository](https://github.com/RomanSoproniuk/online-book-store/assets/151533079/656a95b0-16e1-4da6-836c-5d824fa19ec5)
![service](https://github.com/RomanSoproniuk/online-book-store/assets/151533079/85835e71-5051-4c23-b7fb-e26b95966b13)

2024-03-29 23:17 UTC, MAMentorFX requested changes

2024-03-29 23:17 UTC, MAMentorFX commented on src/test/java/book/store/onlinebookstore/repository/BookRepositoryTest.java
> +        String actualTitle = allByCategoriesId.get(0).getTitle();
extract allByCategoriesId.get(0) to local variable.

2024-03-29 23:17 UTC, MAMentorFX commented on src/test/java/book/store/onlinebookstore/controller/CategoryControllerTest.java
> +        Assertions.assertEquals(actual.getId(), categoryId);
extract to local variable actual.getId()

2024-03-29 23:17 UTC, MAMentorFX commented on src/test/java/book/store/onlinebookstore/service/BookServiceTest.java
> +    }
unreadable, use constructors. Also suggest @BeforeAll for such logic. Do the same for all similar test classes

2024-03-29 23:17 UTC, MAMentorFX commented on src/test/resources/database/books/add-book-for-delete.sql
> +VALUES (3, 'SadokKoloHatu', 'Shevchenko', 50, '43623uefhef723', 'Awesome', 'SuperImage');
```suggestion
VALUES (3, 'SadokKoloHatu', 'Shevchenko', 50, '43623uefhef723', 'Awesome', 'SuperImage');

```
dont forget empty line. Do the same for each .sql

2024-03-30 19:57 UTC, RomanSoproniuk commented on src/test/java/book/store/onlinebookstore/service/BookServiceTest.java
> +    }
![Screenshot_1](https://github.com/RomanSoproniuk/online-book-store/assets/151533079/162c886b-83c0-458a-a454-cce7bd83ae45)
Is that better, for real?

2024-03-31 10:54 UTC, okuzan commented on src/test/java/book/store/onlinebookstore/service/BookServiceTest.java
> +    }
this is more or less a matter of personal code style preference, but here I tend to the second option, setters are just too much visual clutter. You can opt to use builders if you don't like constructors, seems like a compromise

2024-03-31 10:56 UTC, okuzan requested changes
why the change?
![image](https://github.com/RomanSoproniuk/online-book-store/assets/49767049/86c8044c-c12b-4ffc-8eeb-4b38ccb9e00f)

2024-03-31 11:56 UTC, okuzan approved these changes

2024-04-08 13:15 UTC, merged